[2022-03-21 04:12:39,307] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.download_stocks_list scheduled__2022-03-20T00:00:00+00:00 [queued]>
[2022-03-21 04:12:39,325] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.download_stocks_list scheduled__2022-03-20T00:00:00+00:00 [queued]>
[2022-03-21 04:12:39,326] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-21 04:12:39,327] {taskinstance.py:1239} INFO - Starting attempt 8 of 8
[2022-03-21 04:12:39,329] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-21 04:12:39,344] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_stocks_list> on 2022-03-20 00:00:00+00:00
[2022-03-21 04:12:39,350] {standard_task_runner.py:52} INFO - Started process 562 to run task
[2022-03-21 04:12:39,355] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'download_stocks_list', 'scheduled__2022-03-20T00:00:00+00:00', '--job-id', '6664', '--raw', '--subdir', 'DAGS_FOLDER/daily_stocks_dag.py', '--cfg-path', '/tmp/tmpqsvlktu2', '--error-file', '/tmp/tmpuxpixki4']
[2022-03-21 04:12:39,356] {standard_task_runner.py:77} INFO - Job 6664: Subtask download_stocks_list
[2022-03-21 04:12:39,429] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.download_stocks_list scheduled__2022-03-20T00:00:00+00:00 [running]> on host 9578924324f4
[2022-03-21 04:12:39,503] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=download_stocks_list
AIRFLOW_CTX_EXECUTION_DATE=2022-03-20T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-20T00:00:00+00:00
[2022-03-21 04:12:39,505] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-03-21 04:12:39,507] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python3 /opt/***/dags/py_scripts/get_daily_stocks.py 2022-03-20']
[2022-03-21 04:12:39,521] {subprocess.py:85} INFO - Output:
[2022-03-21 04:12:40,026] {subprocess.py:89} INFO - Traceback (most recent call last):
[2022-03-21 04:12:40,027] {subprocess.py:89} INFO -   File "/opt/***/dags/py_scripts/get_daily_stocks.py", line 2, in <module>
[2022-03-21 04:12:40,028] {subprocess.py:89} INFO -     from flatten_json import flatten
[2022-03-21 04:12:40,028] {subprocess.py:89} INFO - ModuleNotFoundError: No module named 'flatten_json'
[2022-03-21 04:12:40,074] {subprocess.py:93} INFO - Command exited with return code 1
[2022-03-21 04:12:40,089] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-03-21 04:12:40,097] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=data_ingestion_gcs_dag, task_id=download_stocks_list, execution_date=20220320T000000, start_date=20220321T041239, end_date=20220321T041240
[2022-03-21 04:12:40,114] {standard_task_runner.py:92} ERROR - Failed to execute job 6664 for task download_stocks_list
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-03-21 04:12:40,133] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-03-21 04:12:40,167] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
