[2022-03-16 23:42:06,383] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: pbp_bucket_ingestion_dag.get_pbp_data scheduled__2013-03-14T04:00:00+00:00 [queued]>
[2022-03-16 23:42:06,549] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: pbp_bucket_ingestion_dag.get_pbp_data scheduled__2013-03-14T04:00:00+00:00 [queued]>
[2022-03-16 23:42:06,557] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-16 23:42:06,560] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-03-16 23:42:06,565] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-16 23:42:06,636] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): get_pbp_data> on 2013-03-14 04:00:00+00:00
[2022-03-16 23:42:06,669] {standard_task_runner.py:52} INFO - Started process 1079 to run task
[2022-03-16 23:42:06,684] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'pbp_bucket_ingestion_dag', 'get_pbp_data', 'scheduled__2013-03-14T04:00:00+00:00', '--job-id', '4959', '--raw', '--subdir', 'DAGS_FOLDER/pbp_ingestion_dag.py', '--cfg-path', '/tmp/tmpqib5oyfl', '--error-file', '/tmp/tmp7eweqtbf']
[2022-03-16 23:42:06,701] {standard_task_runner.py:77} INFO - Job 4959: Subtask get_pbp_data
[2022-03-16 23:42:06,952] {logging_mixin.py:109} INFO - Running <TaskInstance: pbp_bucket_ingestion_dag.get_pbp_data scheduled__2013-03-14T04:00:00+00:00 [running]> on host 18c4eae34c61
[2022-03-16 23:42:07,118] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-03-16 23:42:07,186] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=pbp_bucket_ingestion_dag
AIRFLOW_CTX_TASK_ID=get_pbp_data
AIRFLOW_CTX_EXECUTION_DATE=2013-03-14T04:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2013-03-14T04:00:00+00:00
[2022-03-16 23:42:08,241] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/pbp_ingestion_dag.py", line 66, in get_pbp_data
    upload_json_object(r, f'{GCS_PATH_TEMPLATE}/game_{game_id}.json')
  File "/opt/airflow/dags/pbp_ingestion_dag.py", line 19, in upload_json_object
    BUCKET = storage_client.get_bucket(BUCKET_NAME)
NameError: name 'storage_client' is not defined
[2022-03-16 23:42:08,279] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=pbp_bucket_ingestion_dag, task_id=get_pbp_data, execution_date=20130314T040000, start_date=20220316T234206, end_date=20220316T234208
[2022-03-16 23:42:08,416] {standard_task_runner.py:92} ERROR - Failed to execute job 4959 for task get_pbp_data
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/pbp_ingestion_dag.py", line 66, in get_pbp_data
    upload_json_object(r, f'{GCS_PATH_TEMPLATE}/game_{game_id}.json')
  File "/opt/airflow/dags/pbp_ingestion_dag.py", line 19, in upload_json_object
    BUCKET = storage_client.get_bucket(BUCKET_NAME)
NameError: name 'storage_client' is not defined
[2022-03-16 23:42:08,463] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-03-16 23:42:08,672] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
