[2022-03-16 23:31:56,684] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: pbp_bucket_ingestion_dag.get_pbp_data scheduled__2012-04-25T04:00:00+00:00 [queued]>
[2022-03-16 23:31:56,759] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: pbp_bucket_ingestion_dag.get_pbp_data scheduled__2012-04-25T04:00:00+00:00 [queued]>
[2022-03-16 23:31:56,760] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-16 23:31:56,762] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-03-16 23:31:56,763] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-16 23:31:56,797] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): get_pbp_data> on 2012-04-25 04:00:00+00:00
[2022-03-16 23:31:56,814] {standard_task_runner.py:52} INFO - Started process 140 to run task
[2022-03-16 23:31:56,826] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'pbp_bucket_ingestion_dag', 'get_pbp_data', 'scheduled__2012-04-25T04:00:00+00:00', '--job-id', '4628', '--raw', '--subdir', 'DAGS_FOLDER/pbp_ingestion_dag.py', '--cfg-path', '/tmp/tmpltbcpmxz', '--error-file', '/tmp/tmpiou0g9uc']
[2022-03-16 23:31:56,831] {standard_task_runner.py:77} INFO - Job 4628: Subtask get_pbp_data
[2022-03-16 23:31:57,031] {logging_mixin.py:109} INFO - Running <TaskInstance: pbp_bucket_ingestion_dag.get_pbp_data scheduled__2012-04-25T04:00:00+00:00 [running]> on host ad8b7b7ebf62
[2022-03-16 23:31:57,122] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-03-16 23:31:57,161] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=pbp_bucket_ingestion_dag
AIRFLOW_CTX_TASK_ID=get_pbp_data
AIRFLOW_CTX_EXECUTION_DATE=2012-04-25T04:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2012-04-25T04:00:00+00:00
[2022-03-16 23:31:57,991] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/pbp_ingestion_dag.py", line 65, in get_pbp_data
    upload_json_object(r, f'{GCS_PATH_TEMPLATE}/game_{game_id}.json')
  File "/opt/airflow/dags/pbp_ingestion_dag.py", line 19, in upload_json_object
    blob = BUCKET.blob(filename)
AttributeError: 'str' object has no attribute 'blob'
[2022-03-16 23:31:58,013] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=pbp_bucket_ingestion_dag, task_id=get_pbp_data, execution_date=20120425T040000, start_date=20220316T233156, end_date=20220316T233158
[2022-03-16 23:31:58,037] {standard_task_runner.py:92} ERROR - Failed to execute job 4628 for task get_pbp_data
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/pbp_ingestion_dag.py", line 65, in get_pbp_data
    upload_json_object(r, f'{GCS_PATH_TEMPLATE}/game_{game_id}.json')
  File "/opt/airflow/dags/pbp_ingestion_dag.py", line 19, in upload_json_object
    blob = BUCKET.blob(filename)
AttributeError: 'str' object has no attribute 'blob'
[2022-03-16 23:31:58,062] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-03-16 23:31:58,114] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
