[2022-03-18 04:46:39,388] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: pbp_bucket_ingestion_dag.get_pbp_data scheduled__2010-03-03T04:00:00+00:00 [queued]>
[2022-03-18 04:46:39,434] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: pbp_bucket_ingestion_dag.get_pbp_data scheduled__2010-03-03T04:00:00+00:00 [queued]>
[2022-03-18 04:46:39,436] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-18 04:46:39,438] {taskinstance.py:1239} INFO - Starting attempt 4 of 5
[2022-03-18 04:46:39,441] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-18 04:46:39,498] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): get_pbp_data> on 2010-03-03 04:00:00+00:00
[2022-03-18 04:46:39,508] {standard_task_runner.py:52} INFO - Started process 631 to run task
[2022-03-18 04:46:39,526] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'pbp_bucket_ingestion_dag', 'get_pbp_data', 'scheduled__2010-03-03T04:00:00+00:00', '--job-id', '6303', '--raw', '--subdir', 'DAGS_FOLDER/pbp_ingestion_dag.py', '--cfg-path', '/tmp/tmpvscaygh8', '--error-file', '/tmp/tmp1z0zg5tb']
[2022-03-18 04:46:39,537] {standard_task_runner.py:77} INFO - Job 6303: Subtask get_pbp_data
[2022-03-18 04:46:39,705] {logging_mixin.py:109} INFO - Running <TaskInstance: pbp_bucket_ingestion_dag.get_pbp_data scheduled__2010-03-03T04:00:00+00:00 [running]> on host a2ba0547c319
[2022-03-18 04:46:39,891] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=pbp_bucket_ingestion_dag
AIRFLOW_CTX_TASK_ID=get_pbp_data
AIRFLOW_CTX_EXECUTION_DATE=2010-03-03T04:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2010-03-03T04:00:00+00:00
[2022-03-18 04:46:44,600] {local_task_job.py:212} WARNING - State of this instance has been externally set to None. Terminating instance.
[2022-03-18 04:46:44,618] {process_utils.py:124} INFO - Sending Signals.SIGTERM to group 631. PIDs of all processes in the group: [631]
[2022-03-18 04:46:44,631] {process_utils.py:75} INFO - Sending the signal Signals.SIGTERM to group 631
[2022-03-18 04:46:44,641] {taskinstance.py:1408} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-03-18 04:46:44,645] {python.py:175} INFO - Done. Returned value was: None
[2022-03-18 04:46:44,679] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=pbp_bucket_ingestion_dag, task_id=get_pbp_data, execution_date=20100303T040000, start_date=20220317T020147, end_date=20220318T044644
[2022-03-18 04:46:44,776] {process_utils.py:70} INFO - Process psutil.Process(pid=631, status='terminated', exitcode=0, started='04:46:38') (631) terminated with exit code 0
[2022-03-18 04:53:11,189] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: pbp_bucket_ingestion_dag.get_pbp_data scheduled__2010-03-03T04:00:00+00:00 [queued]>
[2022-03-18 04:53:11,344] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: pbp_bucket_ingestion_dag.get_pbp_data scheduled__2010-03-03T04:00:00+00:00 [queued]>
[2022-03-18 04:53:11,346] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-18 04:53:11,366] {taskinstance.py:1239} INFO - Starting attempt 4 of 5
[2022-03-18 04:53:11,368] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-18 04:53:11,713] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): get_pbp_data> on 2010-03-03 04:00:00+00:00
[2022-03-18 04:53:19,345] {standard_task_runner.py:52} INFO - Started process 238 to run task
