[2022-03-18 04:53:10,698] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: pbp_bucket_ingestion_dag.get_pbp_data scheduled__2010-03-22T04:00:00+00:00 [queued]>
[2022-03-18 04:53:10,907] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: pbp_bucket_ingestion_dag.get_pbp_data scheduled__2010-03-22T04:00:00+00:00 [queued]>
[2022-03-18 04:53:10,936] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-18 04:53:10,945] {taskinstance.py:1239} INFO - Starting attempt 4 of 5
[2022-03-18 04:53:10,957] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-18 04:53:11,214] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): get_pbp_data> on 2010-03-22 04:00:00+00:00
[2022-03-18 04:53:11,701] {standard_task_runner.py:52} INFO - Started process 223 to run task
[2022-03-18 04:53:13,466] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'pbp_bucket_ingestion_dag', 'get_pbp_data', 'scheduled__2010-03-22T04:00:00+00:00', '--job-id', '6322', '--raw', '--subdir', 'DAGS_FOLDER/pbp_ingestion_dag.py', '--cfg-path', '/tmp/tmpg8hujgvz', '--error-file', '/tmp/tmp0vu3rqj3']
[2022-03-18 04:53:13,662] {standard_task_runner.py:77} INFO - Job 6322: Subtask get_pbp_data
